## 1-D numpy array
* can contain only one type of variables(float,int,str)
* numpy arrays are upto 10x fast then normal python list

In [3]:
import numpy as np
a=np.array([1,2,3,4])

print(type(a))
print(a.shape)                           # shape != row,coloumn

a[0]=1234
print(a)

<class 'numpy.ndarray'>
(4,)
[1234    2    3    4]


## 2D- numpy array
> ### [ [.........] ] == matrix  (rank 2),  [..........] == array (rank 1)

* the format is [[row],[row]]
* accessing element is same as that of matrix 

In [31]:
import numpy as np
twod=np.array([[1,2,3],[4,5,6]])
print(twod)                 
print("shape of array is {}".format(twod.shape))             # this shows (rows,colounm

[[1 2 3]
 [4 5 6]]
shape of array is (2, 3)


In [32]:
zeros=np.zeros((2,3))
print(zeros)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [37]:
full=np.full((3,4),2.0)
print(full)


[[ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]


In [38]:
ones=np.ones((3,2))
print(ones)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [39]:
# creates a matrix with diagonal element 1 rest zero
eye=np.eye(3,5)
print(eye)
eye.shape

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]


(3, 5)

In [65]:
import numpy.random as rp
# creates an array of random floats between 0 and 1
rand=rp.random((3,3))
print(rand)

[[ 0.08948355  0.6627442   0.53567285]
 [ 0.87157925  0.8905996   0.64976038]
 [ 0.12685296  0.30510042  0.18912331]]


In [66]:
# generate matrix of floats
w=rp.uniform(low=-10.0,high=7.0,size=(5,3))
print(w)

[[-2.81239755 -3.52608893  4.98336326]
 [-2.78913869 -8.61891329 -9.43463412]
 [-1.07027013 -0.98064643 -7.59688693]
 [-9.36352074 -0.18328779 -0.02265523]
 [-2.1128412   6.95327662 -9.91910111]]


In [71]:
# generate matrix of integer 
inte=rp.randint(low=-2,high=4,size=(2,3))
print(inte)

[[-2  3 -1]
 [ 2  1  2]]


## Slice Indexing
* it *just* gives refrence of sliced part to new variable it did't produce new array

* to create a copy of sliced part use ``` new_slice= np.array(original[:2,1,3])```


In [107]:
import numpy as np
root=np.random.randint(low=1,high=20,size=(4,5))
print(type(root))
root

<class 'numpy.ndarray'>


array([[13, 18, 15,  9, 15],
       [18,  4,  7, 18, 18],
       [ 8,  4, 17,  7,  9],
       [ 6, 15,  4,  9,  7]])

In [108]:
refrence_slice=root[1:3,2:]
print("refrence_slice:\n",refrence_slice,"\n")

refrence_slice[0,1]=-999

print("refrence_slice after modifying:\n",refrence_slice,"\n")
print("root array:\n",root)
# Thus changing a value in refrence_slice changes original variable in root

refrence_slice:
 [[ 7 18 18]
 [17  7  9]] 

refrence_slice after modifying:
 [[   7 -999   18]
 [  17    7    9]] 

root array:
 [[  13   18   15    9   15]
 [  18    4    7 -999   18]
 [   8    4   17    7    9]
 [   6   15    4    9    7]]
