# <span style="color:green"> Boolean Indexing <span>

In [8]:
import numpy as np
arr=np.random.randint(10,30,(4,5))          # random array (low,high,size)
print(arr)

[[14 18 10 15 29]
 [29 15 11 10 23]
 [19 29 23 19 12]
 [23 25 23 20 23]]


In [9]:
filter = (arr>20)
filter

array([[False, False, False, False,  True],
       [ True, False, False, False,  True],
       [False,  True,  True, False, False],
       [ True,  True,  True, False,  True]], dtype=bool)

In [11]:
# gives an numpy array of all element greater then 20
arr[filter]

array([29, 29, 23, 29, 23, 23, 25, 23, 23])

In [12]:
# direct method / shortcut
arr[arr>20]

array([29, 29, 23, 29, 23, 23, 25, 23, 23])

In [14]:
# element between 15 and 25
arr[(arr>15) & (arr<25)]

array([18, 23, 19, 23, 19, 23, 23, 20, 23])

In [17]:
# finding even numbers and adding 100 to them
print(arr[arr%2==0])
arr[arr%2==0] += 100
arr

[114 118 110 110 112 120]


array([[214, 218, 210,  15,  29],
       [ 29,  15,  11, 210,  23],
       [ 19,  29,  23,  19, 212],
       [ 23,  25,  23, 220,  23]])

# <span style="color:green"> Changing dtype </span>

In [25]:
import numpy as np
# np.int64 and np.float64
np.array(([1.7,2,3.6],[4.2,5,6]), dtype=np.int64)

array([[1, 2, 3],
       [4, 5, 6]])

# <span style="color:green"> Arithmetic Operations</span>

In [38]:
x=np.array([[1,1,1],[2,2,2],[3,3,3]])
y=np.zeros((3,3))
y += 1              # y=np.ones((3,3))
print(y)

print(y/x)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.          1.          1.        ]
 [ 0.5         0.5         0.5       ]
 [ 0.33333333  0.33333333  0.33333333]]


In [34]:
# square root and exponent
sql=np.array([[2,3,4],[25,144,169],[441,484,529]])
sq_root=np.sqrt(sql)
print(sq_root)
expo=np.exp(sq_root)
expo

[[  1.41421356   1.73205081   2.        ]
 [  5.          12.          13.        ]
 [ 21.          22.          23.        ]]


array([[  4.11325038e+00,   5.65223367e+00,   7.38905610e+00],
       [  1.48413159e+02,   1.62754791e+05,   4.42413392e+05],
       [  1.31881573e+09,   3.58491285e+09,   9.74480345e+09]])

# <span style="color:green"> Statistical Operations</span>

In [59]:
import numpy as np
stats=np.random.randint(5,11,(3,3))
stats

array([[ 7,  8,  5],
       [ 9,  9, 10],
       [10,  5,  9]])

In [63]:
# mean of rows (axis=1)
print(np.mean(stats,axis=1))

# mean of colunm (axis=0)
print(stats.mean(axis=0))

# sum of array of eachrow
print(stats.sum(axis=1))

# median
print(np.median(stats))

[ 6.66666667  9.33333333  8.        ]
[ 8.66666667  7.33333333  8.        ]
[20 28 24]
9.0


In [67]:
# sorting changes the underlying array
unsort=np.random.randint(-10,15,(3,4))
print(unsort)

unsort.sort()
print(unsort)

[[-2  2 11 -6]
 [ 4  8 -8 12]
 [13 -7  0  3]]
[[-6 -2  2 11]
 [-8  4  8 12]
 [-7  0  3 13]]


# <span style="color:green">Transpose</span>

In [71]:
import numpy as np
u=np.random.random((3,5))
print(u)
u.T

[[ 0.54568078  0.24976057  0.53972015  0.81729103  0.77510837]
 [ 0.87451006  0.60445959  0.53687692  0.24677229  0.55187807]
 [ 0.46656142  0.65893773  0.09944682  0.00996796  0.95237512]]


array([[ 0.54568078,  0.87451006,  0.46656142],
       [ 0.24976057,  0.60445959,  0.65893773],
       [ 0.53972015,  0.53687692,  0.09944682],
       [ 0.81729103,  0.24677229,  0.00996796],
       [ 0.77510837,  0.55187807,  0.95237512]])

# <span style="color:green">Broadcasting</span>
* <span style="color:red"> operation of diff size array</span>

In [8]:
import numpy as np
brod=np.zeros((3,4))
y=brod+np.array([1,2,3,4])
y

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

In [11]:
y=y+1000
y

array([[ 1001.,  1002.,  1003.,  1004.],
       [ 1001.,  1002.,  1003.,  1004.],
       [ 1001.,  1002.,  1003.,  1004.]])

In [17]:
# ze=np.array([1,2,3])
# ze=ze.T          WILL NOT WORK MUST BE OF RANK 2
ze=np.array([[5,6,7]])
ze=ze.T
print(ze)

[[5]
 [6]
 [7]]


array([[5, 6, 7]])

In [18]:
brod=brod+ze
brod

array([[ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])